name: Pipeline CI/CD - Sistema Bancário

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    # --- MUDANÇA DEFINITIVA: Padrão Global ---
    defaults:
      run:
        working-directory: ./banco
    # ------------------------------------------

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4

    # Passo de Debug: Mostra o que o GitHub realmente vê
    - name: DEBUG - Verificar Pastas
      working-directory: . 
      run: |
        echo "=== LISTA DE ARQUIVOS NA RAIZ ==="
        ls -la
        echo "=== LISTA DE ARQUIVOS DENTRO DE BANCO ==="
        ls -la banco || echo "A pasta banco não existe!"

    - name: Configurar o Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: './banco/pom.xml'

    - name: Rodar Testes Unitários (Maven)
      run: mvn clean verify

  test-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    
    defaults:
      run:
        working-directory: ./banco

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache-dependency-path: './banco/package-lock.json'

    - name: Instalar Dependências
      run: npm install

    - name: Rodar Testes Cypress
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./banco
        start: npx http-server . -p 8080
        wait-on: 'http://localhost:8080'
